app/ims_central/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('admin/', admin.site.urls),
    path("maintenance/", include("maintenance.urls")),
    path('accounts/', include('allauth.urls')),
]

app/maintenance/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("websites/", views.websites_view, name="websites_view"),
    path("website/<int:website_id>/", views.detail, name="detail"),
    path("website/<int:website_id>/maintenance", views.maintenance, name="maintenance"),
]

app/maintenance/models.py
from datetime import date, datetime, timezone
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.deconstruct import deconstructible
from slugify import slugify

class Tag(models.Model):
    name = models.CharField(max_length=255) 
    def __str__(self):
        return self.name

@deconstructible
class RequireHttpOrHttpsUrl:
    def __call__(self, value):
        if not value.startswith("http://") and not value.startswith("https://"):
            raise ValidationError('Please provide a http or https resource')
        
class MaintenanceTaskCategory(models.Model):
    name = models.CharField(max_length=200, default='TASK CATEGORY NAME')
    description = models.TextField(blank = True)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Maintenance Task Categories"
    
class MaintenanceTaskList(models.Model):
    name = models.CharField(max_length=200, default='TASK LIST NAME')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Maintenance Task Lists"

class MaintenanceTask(models.Model):
    name = models.CharField(max_length=200, default='TASK NAME')
    description = models.TextField(blank = True)
    task_list = models.ManyToManyField(MaintenanceTaskList)
    category = models.ForeignKey(MaintenanceTaskCategory, on_delete=models.CASCADE, blank=True, null=True)
    def __str__(self):
        return self.name

    def slug(self):
        return slugify(self.name)
        
    class Meta:
        verbose_name_plural = "Maintenance Tasks"

class MaintenancePlan(models.Model):
    name = models.CharField(max_length=200, default='PLAN NAME')
    default_task_list = models.ForeignKey(MaintenanceTaskList, on_delete=models.CASCADE, blank=True, null=True)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Maintenance Plans"

class MaintenanceGrade(models.Model):
    name = models.CharField(max_length=200, default='A')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "Website Maintenance Grades"

class Website(models.Model):
    name = models.CharField(max_length=200,  default='Website Name')
    description = models.TextField(blank = True)
    notes = models.TextField(blank = True)
    url = models.URLField(
        max_length=500, null=True,
        validators=[RequireHttpOrHttpsUrl()]
    )
    login_url = models.URLField(
        max_length=500, null=True, blank=True,
        validators=[RequireHttpOrHttpsUrl()]
    )
    testing_url = models.URLField(
        max_length=500, null=True, blank=True,
        validators=[RequireHttpOrHttpsUrl()]
    )
    maintenance_plan = models.ForeignKey(MaintenancePlan, on_delete=models.CASCADE, blank=True, null=True)
    maintenance_grade = models.ForeignKey(MaintenanceGrade, on_delete=models.CASCADE, blank=True, null=True)    
    maintenance_task_list = models.ForeignKey(MaintenanceTaskList, on_delete=models.CASCADE, blank=True, null=True)
    
    tags = models.ManyToManyField('Tag')
    def __str__(self):
        return self.name
    
    def days_since_maintenance(self):
        last_maintenance = WebsiteEvent.objects.filter(name="maintenance", website=self)
        if(len(last_maintenance) > 0):
            dslm = datetime.now(timezone.utc) - last_maintenance.last().created_at
            return dslm.days
        else:
            return 365

class WebsiteEvent(models.Model):
    name = models.CharField(max_length=200, default='Event Name')
    website = models.ForeignKey(Website, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    worker = models.CharField(max_length=200, default='Worker Name')
    data = models.JSONField(blank=True, null=True)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Website Events"

app/maintenance/forms.py
from django import forms

class MaintenanceForm(forms.Form):
    task_data = forms.JSONField(widget=forms.HiddenInput())

app/maintenance/views.py
from django.http import HttpResponse
from django.template import loader
from .models import Website, MaintenanceTaskList, MaintenanceTask, WebsiteEvent, MaintenanceGrade
from .forms import MaintenanceForm

import json
def index(request):
    websites = Website.objects.all()
    a_websites = Website.objects.filter(maintenance_grade=1)
    b_websites = Website.objects.filter(maintenance_grade=2)
    c_websites = Website.objects.filter(maintenance_grade=3)
    d_websites = Website.objects.filter(maintenance_grade=4)
    template = loader.get_template("maintenance/index.html")

    breadcrumbs = [
        {
            "icon": "fas fa-home",
            "title": "Home",
            "link": "/maintenance/"
        }
    ]

    context = {
        "total_websites": websites.count(),
        "a_websites": a_websites.count(),
        "b_websites": b_websites.count(),
        "c_websites": c_websites.count(),
        "d_websites": d_websites.count(),
        "breadcrumbs": breadcrumbs
    }
    return HttpResponse(template.render(context, request))

def websites_view(request):
    websites = Website.objects.all()

    template = loader.get_template("maintenance/website-list.html")
    website_list = []
    breadcrumbs = [
        {
            "icon": "fas fa-home",
            "title": "Home",
            "link": "/maintenance/"
        },
                {
            "icon": "fa-solid fa-globe",
            "title": "Websites",
            "link": "#",
        }
    ]

    for website in websites:
        website_list.append({
            "name": website.name,
            "url": website.url,
            "plan": website.maintenance_plan.name,
            "grade": website.maintenance_grade.name,
            "dsm": website.days_since_maintenance()
        })

    context = {
        "table_data": json.dumps(website_list, default=list),
        "website_list": websites,
        "request": request,
        "breadcrumbs": breadcrumbs
    }


    return HttpResponse(template.render(context, request))

def detail(request, website_id):
    website = Website.objects.get(id=website_id)
    events = WebsiteEvent.objects.filter(website=website)
    template = loader.get_template("maintenance/details.html")

    breadcrumbs = [
        {
            "icon": "fas fa-home",
            "title": "Home",
            "link": "/maintenance/"
        },
                {
            "icon": "fa-solid fa-globe",
            "title": "Websites",
            "link": "/maintenance/websites/",
        },
        {
            "icon": "fa-solid fa-circle-info",
            "title": website.name + " Details",
            "link": "/maintenance/websites/",
        }
    ]

    context = {
        "website": website,
        "website_events": events.order_by('-created_at').values(),
        "breadcrumbs": breadcrumbs
    }
    return HttpResponse(template.render(context, request))


def maintenance(request, website_id):
    website = Website.objects.get(id=website_id)
    grades = MaintenanceGrade.objects.all()
    if request.method == "POST":
        form = MaintenanceForm(request.POST)
        context = {
            "form": form
        }
        template = loader.get_template("maintenance/maintenance-complete.html")

        if form.is_valid():
            event = WebsiteEvent(
                name="maintenance",
                website=website,
                worker=request.user,
                data=form.data['task_data']
            )
            event.save()
            print(event.created_at)
            return HttpResponse(template.render(context, request))
    else:
        tasks = MaintenanceTask.objects.filter(task_list=website.maintenance_task_list)
        template = loader.get_template("maintenance/maintenance-form.html")
        context = {
            "website": website,
            "form": MaintenanceForm(),
            "tasks": tasks,
            "grades": grades
        }
    return HttpResponse(template.render(context, request))

app/maintenance/templates/maintenance/base-clean.html
{% load static %}
<!DOCTYPE html>
<html class="h-full bg-white">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link href="https://cdn.jsdelivr.net/npm/@creativebulma/bulma-tooltip@1.2.0/dist/bulma-tooltip.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"> 
    <title>Central - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'output.css' %}">
  </head>
  <body>
      <main>
        <div>
          {% block content %}{% endblock %}
        </div>
      </main>
  </body>
</html>

app/maintenance/templates/maintenance/base.html
{% load static %}
<!DOCTYPE html>
<html class="h-full bg-white">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link href="https://cdn.jsdelivr.net/npm/@creativebulma/bulma-tooltip@1.2.0/dist/bulma-tooltip.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <title>Central - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'output.css' %}">
  </head>
  <body>
      <main class="columns is-gapless is-fullheight">
        <div class="column is-one-fifth is-fullheight p-5" style="background: #101820;">{% include "maintenance/nav.html" %}</div>
        <div class="column">
          {% include "maintenance/breadcrumbs.html" %}
          {% block content %}{% endblock %}
        </div>
      </main>
  </body>
</html>

app/maintenance/templates/maintenance/breadcrumbs.html
<div class="p-5">
  <nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
      {% for breadcrumb in breadcrumbs %}
      <li {% if forloop.last %}class="is-active"{% endif %}>
        <a href="{{breadcrumb.link}}">
          <span class="icon is-small">
            <i class="{{breadcrumb.icon}}" aria-hidden="true"></i>
          </span>
          <span>{{breadcrumb.title}}</span>
        </a>
      </li>
      {% endfor %}
    </ul>
  </nav>
</div>

app/maintenance/templates/maintenance/details copy.html
{% extends "maintenance/base.html" %}
{% block title %}{{ website.name }}{% endblock %}
{% block page_title %}{{ website.name }}{% endblock %}

{% block content %}
<div class="mt-7 lg:flex lg:items-center lg:justify-between">
  <div class="min-w-0 flex-1">
    <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:truncate sm:text-3xl sm:tracking-tight">{{website.name}}</h2>
    <div class="mt-3 flex flex-col  sm:flex-row sm:flex-wrap sm:space-x-6">
      <div class="mt-2 flex items-center text-sm text-gray-500">
        <svg class="mr-1.5 h-5 w-5 flex-shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M6 3.75A2.75 2.75 0 018.75 1h2.5A2.75 2.75 0 0114 3.75v.443c.572.055 1.14.122 1.706.2C17.053 4.582 18 5.75 18 7.07v3.469c0 1.126-.694 2.191-1.83 2.54-1.952.599-4.024.921-6.17.921s-4.219-.322-6.17-.921C2.694 12.73 2 11.665 2 10.539V7.07c0-1.321.947-2.489 2.294-2.676A41.047 41.047 0 016 4.193V3.75zm6.5 0v.325a41.622 41.622 0 00-5 0V3.75c0-.69.56-1.25 1.25-1.25h2.5c.69 0 1.25.56 1.25 1.25zM10 10a1 1 0 00-1 1v.01a1 1 0 001 1h.01a1 1 0 001-1V11a1 1 0 00-1-1H10z" clip-rule="evenodd" />
          <path d="M3 15.055v-.684c.126.053.255.1.39.142 2.092.642 4.313.987 6.61.987 2.297 0 4.518-.345 6.61-.987.135-.041.264-.089.39-.142v.684c0 1.347-.985 2.53-2.363 2.686a41.454 41.454 0 01-9.274 0C3.985 17.585 3 16.402 3 15.055z" />
        </svg>
        {{website.url}}
      </div>
      <div class="mt-2 flex items-center text-sm text-gray-500">
        <svg class="mr-1.5 h-5 w-5 flex-shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M9.69 18.933l.003.001C9.89 19.02 10 19 10 19s.11.02.308-.066l.002-.001.006-.003.018-.008a5.741 5.741 0 00.281-.14c.186-.096.446-.24.757-.433.62-.384 1.445-.966 2.274-1.765C15.302 14.988 17 12.493 17 9A7 7 0 103 9c0 3.492 1.698 5.988 3.355 7.584a13.731 13.731 0 002.273 1.765 11.842 11.842 0 00.976.544l.062.029.018.008.006.003zM10 11.25a2.25 2.25 0 100-4.5 2.25 2.25 0 000 4.5z" clip-rule="evenodd" />
        </svg>
        {{website.maintenance_plan}}
      </div>
      <div class="mt-2 flex items-center text-sm text-gray-500">
        <svg class="mr-1.5 h-5 w-5 flex-shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path d="M10.75 10.818v2.614A3.13 3.13 0 0011.888 13c.482-.315.612-.648.612-.875 0-.227-.13-.56-.612-.875a3.13 3.13 0 00-1.138-.432zM8.33 8.62c.053.055.115.11.184.164.208.16.46.284.736.363V6.603a2.45 2.45 0 00-.35.13c-.14.065-.27.143-.386.233-.377.292-.514.627-.514.909 0 .184.058.39.202.592.037.051.08.102.128.152z" />
          <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-6a.75.75 0 01.75.75v.316a3.78 3.78 0 011.653.713c.426.33.744.74.925 1.2a.75.75 0 01-1.395.55 1.35 1.35 0 00-.447-.563 2.187 2.187 0 00-.736-.363V9.3c.698.093 1.383.32 1.959.696.787.514 1.29 1.27 1.29 2.13 0 .86-.504 1.616-1.29 2.13-.576.377-1.261.603-1.96.696v.299a.75.75 0 11-1.5 0v-.3c-.697-.092-1.382-.318-1.958-.695-.482-.315-.857-.717-1.078-1.188a.75.75 0 111.359-.636c.08.173.245.376.54.569.313.205.706.353 1.138.432v-2.748a3.782 3.782 0 01-1.653-.713C6.9 9.433 6.5 8.681 6.5 7.875c0-.805.4-1.558 1.097-2.096a3.78 3.78 0 011.653-.713V4.75A.75.75 0 0110 4z" clip-rule="evenodd" />
        </svg>
        {{website.maintenance_grade}}
      </div>
      <div class="mt-2 flex items-center text-sm text-gray-500">
        <svg class="mr-1.5 h-5 w-5 flex-shrink-0 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M5.75 2a.75.75 0 01.75.75V4h7V2.75a.75.75 0 011.5 0V4h.25A2.75 2.75 0 0118 6.75v8.5A2.75 2.75 0 0115.25 18H4.75A2.75 2.75 0 012 15.25v-8.5A2.75 2.75 0 014.75 4H5V2.75A.75.75 0 015.75 2zm-1 5.5c-.69 0-1.25.56-1.25 1.25v6.5c0 .69.56 1.25 1.25 1.25h10.5c.69 0 1.25-.56 1.25-1.25v-6.5c0-.69-.56-1.25-1.25-1.25H4.75z" clip-rule="evenodd" />
        </svg>
        Last maintenance: 
      </div>
    </div>
  </div>
  <div class="mt-5 flex lg:ml-4 lg:mt-0">
    <a class="ml-3 hidden sm:block" href="/admin/maintenance/website/{{website.id}}/change/" target="_blank">
      <button type="button" class="inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
        Edit
      </button>
    </a>
    <a class="ml-3 hidden sm:block" href="{{website.login_url}}" target="_blank">
      <button type="button" class="inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
        Login
      </button>
    </a>
    <a class="ml-3 hidden sm:block" onclick='window.open("/maintenance/website/{{website.id}}/maintenance", "", "width=450,height=1020");'>
      <button type="button" class="inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
        Perform Maintenance
      </button>
    </a>
  </div>
</div>
<div class="container mt-7">
  <div>
    <div class="sm:px-0">
      <h3 class="text-base font-semibold leading-7 text-gray-900">Website Information</h3>
      <p class="mt-1 max-w-2xl text-sm leading-6 text-gray-500">{{website.description}}</p>
    </div>
    <div class="mt-6 border-t border-gray-100">
      <dl class="divide-y divide-gray-100">
        <div class="py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
          <dt class="text-sm font-medium leading-6 text-gray-900">Website URL</dt>
          <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{website.url}}</dd>
        </div>
        <div class="py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
          <dt class="text-sm font-medium leading-6 text-gray-900">Website Notes</dt>
          <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{website.notes}}</dd>
        </div>
        <div class="py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
          <dt class="text-sm font-medium leading-6 text-gray-900">Events</dt>
          <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
            <ul>
              {% if website_events|length < 1 %}
              <li>{{website_events.created_at}}: {{website_events.name}} | {{website_events.worker}}</li>
              {% else %}
              {% for event in website_events %}
              <li>{{event.created_at}}: {{event.name}} | {{event.worker}}</li>
              {% endfor %}
              {% endif %}
            </ul>
          </dd>
        </div>
      </dl>
    </div>
  </div>
</div>

{% endblock %}

app/maintenance/templates/maintenance/maintenance-complete.html
{% extends "maintenance/base-clean.html" %}
{% block title %}{{ website.name }}{% endblock %}
{% block page_title %}{{ website.name }}{% endblock %}

{% block content %}
<div class="container">
    <h1 class="is-size-2 has-text-centered has-text-weight-bold mt-5 pt-5 has-text-success">Maintenance Complete</h1>
    <h2 class="is-size-4 has-text-centered has-text-weight-semibold">You may close this window</h2>
</div>
{% endblock %}

app/maintenance/templates/maintenance/maintenance-form.html
{% extends "maintenance/base-clean.html" %}
{% block title %}{{ website.name }}{% endblock %}
{% block page_title %}{{ website.name }}{% endblock %}

{% block content %}
<section class="hero is-info">
  <div class="container">
    <div class="px-5 py-6">
      <p class="title">
        {{website.name}}
      </p>
      <div class="subtitle">
        <p class="my-2">Maintenance Form</p>
        <div class="mb-2">
          <span class="is-size-6"><strong>Plan:</strong> {{website.maintenance_plan}}</span>
        </div>
        <div>
          <span class="is-size-6"><strong>Grade:</strong> {{website.maintenance_grade}}</span> | <span class="is-size-6"><strong>Days Since Maintenance:</strong> {{website.days_since_maintenance}}</span>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="container">
  <div class="inner px-5 my-3">
    <form id="task-form">
      {% for task in tasks %}
      <div class="task-box mb-2">
        <div class="task-head is-flex is-justify-content-space-between is-align-items-center">
          <div>
            <input type="checkbox" id="{{task.slug}}" name="{{task.slug}}" style="height:15px;width:15px;">
            <label for="{{task.slug}}" class="is-size-5 has-text-weight-medium has-text-info-dark">{{task.name}}</label>
          </div>
          <div class="button is-small" data-tooltip='Add Note' onclick="toggleNote(this);">
            <span class="icon is-small">
              <i class="fa-solid fa-notes-medical"></i>
            </span>
          </div>
        </div>
        <div class="task-note">
          <textarea id="{{task.slug}}-note" name="{{task.slug}}-note" class="textarea is-medium mt-3" rows="2" cols="50"></textarea>
        </div>
      </div>
      {% endfor %}
      <div class="task-box mb-2 my-3 is-flex is-align-items-center is-justify-content-space-between">
        <div><label for="recommended-grade" class="is-size-5 has-text-weight-medium has-text-info-dark">Maintenance Grade: </label></div>
        <div class="select">
          <select name="recommended-grade">
            {% for grade in grades %}
            <option value="{{grade.name}}" {% if grade.name == website.maintenance_grade.name %}selected{% endif %}>{% if grade.name == website.maintenance_grade.name %}{{grade.name}} (no change){% else %}{{grade.name}} (change){% endif %}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div class="task-box mb-2">
        <label for="optimization-tasks" class="is-size-5 has-text-weight-medium has-text-info-dark">Optimisation Tasks:</label>
        <textarea id="optimization-tasks" name="optimization-tasks" class="textarea is-medium my-3" rows="2" cols="50"></textarea>
      </div>
    </form>
    <div class="pb-5">
      <button onclick="taskForm()" class="button is-success">Submit Maintenance Record</button>
    </div>
    <form action="/maintenance/website/{{website.id}}/maintenance" method="post" id="maintenance-form">{% csrf_token %}{{ form.media }}{{ form }}</form>
    </div>
</div>
<script>
  function taskForm() {
    let object = {};
    let data = new FormData(document.querySelector('#task-form'));
    data.forEach((value, key) => object[key] = value);

    document.querySelector('#id_task_data').value = JSON.stringify(object);
    document.querySelector('#maintenance-form').submit();
  }
  function toggleNote(e) {
    e.style.display = "none";
    e.parentNode.parentNode.classList.add('note');
  }
</script>
{% endblock %}

app/maintenance/templates/maintenance/nav.html
<div class="p-5 is-flex is-flex-direction-column is-justify-content-space-between" style="height:100%;">
  <div class="is-flex is-flex-direction-column p-5">
    <div class="logo-box pb-5 mb-5">
      <img class="" src="https://aldhuybmnp.cloudimg.io/v7/www.imsmarketing.ie/wp-content/uploads/2021/11/ims-marketing-logo-2020.png" alt="IMS MARKETING">
    </div>
    <div class="menu-box">
      <ul>
        <li class="mb-3">
          <a href="/maintenance/" class="menu-link is-size-3 has-text-weight-medium has-text-light">Home</a>
        </li>
        <li class="mb-3">
          <a href="/maintenance/websites/" class="menu-link is-size-3 has-text-weight-medium has-text-light">Websites</a>
        </li>
      </ul>
    </div>
  </div>
  <div class="is-flex is-flex-direction-column p-5">
    <div class="user-box">
        <a href="#" class="has-text-light is-size-4 is-flex is-align-items-center">
          <img src="https://placehold.co/50x50" style="border-radius: 50%;">
          <span class="ml-4">{{ request.user }}</span>
        </a>
    </div>
  </div>
</div>